### ISSUE TITLE
pydantic ConfigDict prevents passing new config entries via the command line override

### ISSUE THREAD

**Issue by mpvginde** [ecmwf/anemoi-inference#199]
Hi,

I have the following use-case:  
I want to run LAM-inference for different dates, where all the initial states are stored in one `zarr`-file and the boundary conditions are stored in a `zarr`-file per forecast-run. 

To prevent me from rewriting the config for every inference run, I have the following config setup:
```yaml
checkpoint: 763af34c15134d1da1916f15ec502ada/inference-anemoi-by_epoch-epoch_011-step_150456.ckpt

input:
  test:
    use_original_paths: false

date: 2020-01-02T00:00:00
lead_time: 60h

input:
  dataset:
    cutout:
      - dataset: /datasets/ifs/ic/ifs-analysis_2024_v2.zarr

 output:
  extract_lam:
    lam: '0/lam_0'
    output:
      netcdf:
        path ./inference/2020010200.nc
```

The actual forecast date and boundary dataset are set by using the overrides e.g.
```bash
anemoi-inference run ./config/lam-512-600km-ifs.yaml \
  "date=2024-01-22T00:00:00"  \
  "+input.dataset.cutout={dataset: /datasets/ifs/lbc/ifs-lbc_20240122_00_v2.zarr}"  \
  "output.extract_lam.output.netcdf.path=./output/ifs-coupled/ifs-coupled_20240122_00.nc"
```

When I try this `pydantic` complains with
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Configuration
+input
  Extra inputs are not permitted [type=extra_forbidden, input_value={'dataset': {'cutout': '{..._20240122_00_v2.zarr}'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden
2025-04-03 14:43:13 ERROR 
💣 1 validation error for Configuration
+input
  Extra inputs are not permitted [type=extra_forbidden, input_value={'dataset': {'cutout': '{..._20240122_00_v2.zarr}'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden
2025-04-03 14:43:13 ERROR 💣 Exiting
```

I guess this is because the `model_config` set here with keyword `extra="forbid"`
https://github.com/ecmwf/anemoi-inference/blob/a082af43ee214ad956315ef357f5d8d68842a662/src/anemoi/inference/config/__init__.py#L32-L36

I tested with  `extra="allow"` and this seems to remove the pydantic error, but the extra dataset provided through the override is never loaded/added to the config. 

KR,
Michiel
