### ISSUE TITLE
Variable interpolations in yaml configs

### ISSUE THREAD

**Issue by bdvllrs** [ecmwf/anemoi-inference#243]
### Is your feature request related to a problem? Please describe.

In other anemoi projects (anemoi-core) we can use interpolation in the config file thanks to OmegaConf. As this project doesn't use it, it's impossible to use interpolation in config.

For example:
```yaml
checkpoint: inference-aifs-0.2.1-anemoi.ckpt

date: 2024-01-31T00:00:00

input:
  dataset:
    cutout:
      - dataset: ${oc.env:$SCRATCH}/path/to/analysis_20240101_00.zarr  # use environment variable
 ```

If this is of interest, I can provide a PR for this.

### Describe the solution you'd like

Use OmegaConf or hydra to load the config, before passing the resolved object to pydantic:
```python
import OmegaConf

from pydantic import BaseModel


class Configuration(BaseModel):
    ...

Configuration.model_validate(OmegaConf.to_container(cfg, resolve=True))
```

This would also simplily the code for loading the config as OmegaConf already can merge several configs.

### Describe alternatives you've considered

If we don't want to add OmegaConf as a dependency here, I have worked on this in the past here: https://github.com/bdvllrs/cfg-tools and I could integrate an updated version here (or maybe in anemoi-utils?).

It's a parser that look for `#{[fn:]val}` (but I can adapt it to `${}` for parity with omegaconf) in the fields and replace it by the output of `fn(val)`. You can see some examples [here](https://github.com/bdvllrs/cfg-tools/tree/main/tests).

There is also a way to integrate it with pydantic to apply it to all fields.

### Organisation

Météo-France
