### ISSUE TITLE
First mask of cutout input is not applied

### ISSUE THREAD

**Issue by bdvllrs** [ecmwf/anemoi-inference#248]
### What happened?

In the Cutout input file, the mask of the first source is never applied.

For example with the following config:
```yaml
input:
  cutout:
    global:
        grib: path/to/global.grib
    lam_0:
        grib: path/to/lam_0.grib
```

The cutout mask of `global` is never applied. 
Note that in this instance, reversing the order of global and lam_0 would fix it, but there could be settings with multiple lam.
This also differs from the implementation in anemoi-datasets where the mask is applied everywhere (e.g. [here](https://github.com/ecmwf/anemoi-datasets/blob/f9769d7944738ecbedb6b3cc1f78cd26de36a73f/src/anemoi/datasets/data/grids.py#L544)).

I will provide an initial PR with a fix applying the mask everywhere.

### What are the steps to reproduce the bug?

Make an inference 

### Version

main

### Platform (OS and architecture)

Linux ac6-102.bullx 4.18.0-477.43.1.el8_8.x86_64 # 1 SMP Thu Jan 4 10:30:57 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```shell

```

### Organisation

Météo-France
